name: flutter_tcp_client
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  riverpod: ^0.14.0+3

dev_dependencies:
  flutter_riverpod: ^0.14.0+3
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
